#!/bin/bash
# This file is used for executing synful management commands
# on unix machines.

run ()
{
    cd public;
    php index.php "$@";
    cd ..;
}

if [ ! -f ./src/Synful/Synful.php ]; then
    echo "Must be run from Synful root directory.";
else
    if [ ! -z "$1" ]; then
        if [[ "$1" == "install" ]]; then
            composer install --no-scripts --no-dev;
            run -migrate up
            composer dumpautoload -o
        elif [[ "$1" == "update" ]]; then
            composer update;
            composer dumpautoload -o
        else
            run "$@";
        fi;
    else
        run "$@";
    fi;
fi
