#!/bin/bash
# This file is used for executing synful management commands
# on unix machines.

run ()
{
    cd public;
    php index.php "$@";
    cd ..;
}

if [ ! -f ./src/Synful/Synful.php ]; then
    echo "Must be run from Synful root directory.";
else
    if [ ! -z "$1" ]; then
        if [[ "$1" == "install" ]]; then
            composer install --no-scripts --no-dev;
        elif [[ "$1" == "update" ]]; then
            composer update;
        elif [[ "$1" == "vagrant" ]]; then
            if [ ! -z "$2" ]; then
	            vagrant "$@";
            else
		        if [ -d .vagrant ]; then
                    vagrant destroy;
		            rm -r .vagrant
                else
                    vagrant up;
                fi;
            fi;
        else
            run "$@";
        fi;
    else
        run "$@";
    fi;
fi
